create schema SD_SQL;

CREATE TABLE student
(id int not null,
name varchar(25) not null,
percentage float not null,
grade char not null);

describe student;
-- CHANGE TABLE NAME USE ALTER COMMAD AND USED KEYRWORD RENAME --
ALTER TABLE student RENAME TO tops;
ALTER TABLE tops RENAME TO student;

-- CHANGE COLUMN NAME USE ALTER COMMAND AND USED KEYWORD RENAME --
ALTER TABLE student RENAME COLUMN id TO no_id;

-- ADD COLUMN USE ALTER COMMAND AND USED KEYWORD ADD --
ALTER TABLE student ADD COLUMN city varchar(25) NOT NULL;
ALTER TABLE student ADD COLUMN state varchar(25) NOT NULL;


-- ADD COLUMN AT SPECIFIC POSITION USE ALTER COMMAND AND USED  KEYWORD MODIFY AND AFTER--
ALTER TABLE student ADD COLUMN city varchar(25) NOT NULL AFTER grade;
ALTER TABLE student ADD COLUMN pincode INT NOT NULL AFTER city;
ALTER TABLE student ADD COLUMN ranks int;

--  CHANGE DATATYPE USE ALTER COMMAND AND USED KEYWORD MODIFY--
ALTER TABLE student MODIFY pincode varchar(25);
ALTER TABLE student MODIFY pincode int; 

-- ADD NEW CONSTRAIN USED ALTER COMMAND AND USED KEYWORD MODIFY--
ALTER TABLE student MODIFY pincode int NOT NULL;
ALTER TABLE student MODIFY ranks int NOT NULL;

-- REMOVE CONSTRAINT USE ALTER COMMAND AND USED KEYWORD MODIFY--
ALTER TABLE student MODIFY city varchar (25);

-- DELETE COLUMN USE ALTER COMMAND AND USED KEYWORD DROP--
ALTER TABLE student DROP COLUMN city;
ALTER TABLE student DROP COLUMN pincode;
ALTER TABLE student DROP COLUMN state;
-- DROP TABLE
DROP TABLE student;

-- DROP SCHEMA 
DROP SCHEMA SD_SQL;